<a href="https://colab.research.google.com/github/RiyaSharma82308/NLP/blob/main/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("learning NLP here")
#

learning NLP here


In [2]:
!nvidia-smi -L

/bin/bash: nvidia-smi: command not found


In [3]:
#helper functions for the notebook imported from github
!wget https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/extras/helper_functions.py
from helper_functions import unzip_data, create_tensorboard_callback , plot_loss_curves,compare_historys

--2023-04-25 14:16:53--  https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/extras/helper_functions.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10246 (10K) [text/plain]
Saving to: ‘helper_functions.py’

helper_functions.py 100%[===================>]  10.01K  --.-KB/s    in 0s      

2023-04-25 14:16:53 (62.1 MB/s) - ‘helper_functions.py’ saved [10246/10246]



# Get the text dataset


In [4]:
!wget https://storage.googleapis.com/ztm_tf_course/nlp_getting_started.zip
#this data taken from kaggle


--2023-04-25 14:17:03--  https://storage.googleapis.com/ztm_tf_course/nlp_getting_started.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 142.250.99.128, 74.125.20.128, 108.177.98.128, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.250.99.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 607343 (593K) [application/zip]
Saving to: ‘nlp_getting_started.zip’

nlp_getting_started 100%[===================>] 593.11K  --.-KB/s    in 0.02s   

2023-04-25 14:17:03 (25.3 MB/s) - ‘nlp_getting_started.zip’ saved [607343/607343]



In [5]:
unzip_data("nlp_getting_started.zip")   #unzip the data

In [6]:
# visualizing the text dataset

In [7]:
import pandas as pd
train_df = pd.read_csv("train.csv")
test_df=pd.read_csv("test.csv")
train_df.head()

id keyword location                                               text  \
0   1     NaN      NaN  Our Deeds are the Reason of this #earthquake M...   
1   4     NaN      NaN             Forest fire near La Ronge Sask. Canada   
2   5     NaN      NaN  All residents asked to 'shelter in place' are ...   
3   6     NaN      NaN  13,000 people receive #wildfires evacuation or...   
4   7     NaN      NaN  Just got sent this photo from Ruby #Alaska as ...   

   target  
0       1  
1       1  
2       1  
3       1  
4       1

In [8]:
#shuffle training dataframe
train_df_shuffled= train_df.sample(frac=1, random_state=42)
train_df_shuffled.head()

id      keyword               location  \
2644  3796  destruction                    NaN   
2227  3185       deluge                    NaN   
5448  7769       police                     UK   
132    191   aftershock                    NaN   
6845  9810       trauma  Montgomery County, MD   

                                                   text  target  
2644  So you have a new weapon that can cause un-ima...       1  
2227  The f$&amp;@ing things I do for #GISHWHES Just...       0  
5448  DT @georgegalloway: RT @Galloway4Mayor: ‰ÛÏThe...       1  
132   Aftershock back to school kick off was great. ...       0  
6845  in response to trauma Children of Addicts deve...       0

In [9]:
test_df.head()

id keyword location                                               text
0   0     NaN      NaN                 Just happened a terrible car crash
1   2     NaN      NaN  Heard about #earthquake is different cities, s...
2   3     NaN      NaN  there is a forest fire at spot pond, geese are...
3   9     NaN      NaN           Apocalypse lighting. #Spokane #wildfires
4  11     NaN      NaN      Typhoon Soudelor kills 28 in China and Taiwan

In [10]:
train_df.target.value_counts()

0    4342
1    3271
Name: target, dtype: int64

In [11]:
import random
random_index = random.randint(0,len(train_df)-5)
for row in train_df_shuffled[["text","target"]][random_index:random_index+5].itertuples():
  _,text,target=row
  print(f"Target:{target}","(disaster)" if target > 0 else "(not disaster)")
  print(f"text:{text}\n")

Target:0 (not disaster)
text:Womens Handbags Cross Body Geometric Pattern Satchel Totes Shoulder Bags White http://t.co/qvSp6b2qSU http://t.co/0s6ydFrWDQ RT gasparc‰Û_

Target:0 (not disaster)
text:Electrocute yourself

Target:1 (disaster)
text:#BBSNews latest 4 #Palestine &amp; #Israel -  Six Palestinians Kidnapped in West Bank Hebron Home Demolished http://t.co/gne1fW0XHE

Target:0 (not disaster)
text:@VictoriaGittins what do you take me for I'm not a mass murderer! Just the one...

Target:1 (disaster)
text:Trafford Centre film fans angry after Odeon cinema evacuated following false fire alarm http://t.co/pFMn63VnAm http://t.co/vKwqbOJFJc



In [12]:
#train test split
from sklearn.model_selection import train_test_split

In [13]:
train_df_shuffled

id       keyword                        location  \
2644   3796   destruction                             NaN   
2227   3185        deluge                             NaN   
5448   7769        police                              UK   
132     191    aftershock                             NaN   
6845   9810        trauma           Montgomery County, MD   
...     ...           ...                             ...   
5226   7470  obliteration                         Merica!   
5390   7691         panic                             NaN   
860    1242         blood                             NaN   
7603  10862           NaN                             NaN   
7270  10409     whirlwind  Stamford & Cork (& Shropshire)   

                                                   text  target  
2644  So you have a new weapon that can cause un-ima...       1  
2227  The f$&amp;@ing things I do for #GISHWHES Just...       0  
5448  DT @georgegalloway: RT @Galloway4Mayor: ‰ÛÏThe...       1  
132   Aftershock back to school kick off was great. ...       0  
6845  in response to trauma Children of Addicts deve...       0  
...                                                 ...     ...  
5226  @Eganator2000 There aren't many Obliteration s...       0  
5390  just had a panic attack bc I don't have enough...       0  
860   Omron HEM-712C Automatic Blood Pressure Monito...       0  
7603  Officials say a quarantine is in place at an A...       1  
7270  I moved to England five years ago today. What ...       1  

[7613 rows x 5 columns]

In [14]:
train_sentences,val_sentences,train_labels,val_labels=train_test_split(train_df_shuffled["text"].to_numpy(),
                                                                        train_df_shuffled["target"].to_numpy(),
                                                                        test_size=0.1,
                                                                        random_state=42)

In [15]:
len(train_sentences),len(train_labels),len(val_sentences),len(val_labels)

(6851, 6851, 762, 762)

In [16]:
train_sentences[:3]

array(['@mogacola @zamtriossu i screamed after hitting tweet',
       'Imagine getting flattened by Kurt Zouma',
       '@Gurmeetramrahim #MSGDoing111WelfareWorks Green S welfare force ke appx 65000 members har time disaster victim ki help ke liye tyar hai....'],
      dtype=object)

In [17]:
#text vectorization(tokenization)
import tensorflow as tf
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization

In [18]:
# default parameters
text_vectorizer = TextVectorization(max_tokens=None,
                     standardize="lower_and_strip_punctuation",
                     split="whitespace",
                     ngrams=None,
                     output_mode="int",
                     output_sequence_length=None,
                     pad_to_max_tokens=False)

In [19]:
max_vocab_length=10000
max_length=15
text_vectorizer = TextVectorization(max_tokens=max_vocab_length,
                                    output_mode="int",
                                    output_sequence_length=max_length)

In [20]:
text_vectorizer.adapt(train_sentences)

In [21]:
text_vectorizer(["my name is riya sharma uwhfu igdfiu sduhhue jhd ddugf uugr sudy eugh uyhdu dfuhe jdbv dvj"])

<tf.Tensor: shape=(1, 15), dtype=int64, numpy=
array([[ 13, 735,   9,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1]])>

In [22]:
type(train_sentences[0])

str

In [23]:
random_sentence=random.choice(train_sentences)
# type(random_sentence)
print(f"original sentence\n{random_sentence}\
\n\n Vectorized version: ")
text_vectorizer([random_sentence])

original sentence
Battle of the GOATS  https://t.co/ofECs6tcvC

 Vectorized version: 


<tf.Tensor: shape=(1, 15), dtype=int64, numpy=
array([[442,   6,   2,   1,   1,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0]])>

In [24]:
words_in_vocab=text_vectorizer.get_vocabulary()
top_5_words=words_in_vocab[:5]
least_5_words=words_in_vocab[-5:]
print(top_5_words)
print(least_5_words)

['', '[UNK]', 'the', 'a', 'in']
['pages', 'paeds', 'pads', 'padres', 'paddytomlinson1']


In [25]:
#creating an embedding using an embedding layer

In [26]:
from tensorflow.keras import layers
embedding = layers.Embedding(input_dim=max_vocab_length,
                             output_dim = 128,
                             input_length = max_length)

In [27]:
random_sentence = random.choice(train_sentences)
print(random_sentence)
sample_embed = embedding(text_vectorizer([random_sentence]))
sample_embed

Stony Jackson is America's last hope as he leads an army of felons thus and army rejects against the army o Satan - http://t.co/0wbEcdMHQo


<tf.Tensor: shape=(1, 15, 128), dtype=float32, numpy=
array([[[ 0.01390282, -0.00629093,  0.01534471, ..., -0.01532862,
          0.04589588, -0.03887264],
        [-0.04850337, -0.00677452,  0.00871899, ...,  0.04928409,
         -0.02350528, -0.03028825],
        [ 0.04568458,  0.00233682,  0.04018482, ..., -0.03276686,
         -0.04064434, -0.03562825],
        ...,
        [ 0.04535613, -0.04113474, -0.03302699, ...,  0.00469539,
          0.01003237, -0.00632688],
        [-0.01887242,  0.03068877,  0.04222159, ..., -0.01217562,
         -0.01720478,  0.00807868],
        [-0.04110541, -0.03955326,  0.02582761, ...,  0.01054467,
          0.02378384,  0.04561958]]], dtype=float32)>

In [28]:
train_sentences.shape

(6851,)

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
model_0 = Pipeline([("tfidf",TfidfVectorizer()),
                    ("clf",MultinomialNB())])
model_0.fit(train_sentences,train_labels)
baseline_score= model_0.score(val_sentences,val_labels)
print(f" accuracy achieved by baseline model is {baseline_score*100:.2f}")

 accuracy achieved by baseline model is 79.27


In [30]:
baseline_preds=model_0.predict(val_sentences)
baseline_preds[:20]

array([1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1])

In [31]:
# function to evaluate : accuracy,precisiion,recall,f1-score
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
def calculate_results(y_true,y_pred):
  model_accuracy = accuracy_score(y_true,y_pred)*100
  model_precision, model_recall,model_f1, _=precision_recall_fscore_support(y_true,y_pred,average="weighted")
  model_results={"accuracy":model_accuracy,
                 "precision":model_precision,
                 "recall":model_recall,
                 "f1":model_f1}
  return model_results

In [32]:
baseline_results = calculate_results(y_true=val_labels,
                                     y_pred=baseline_preds)
baseline_results

{'accuracy': 79.26509186351706,
 'precision': 0.8111390004213173,
 'recall': 0.7926509186351706,
 'f1': 0.7862189758049549}

In [33]:
 #model 1 : A simple dense model

In [34]:
from helper_functions import create_tensorboard_callback
SAVE_DIR="model_logs"


In [35]:
from tensorflow.keras import layers
inputs = layers.Input(shape=(1,), dtype=tf.string)
x=text_vectorizer(inputs)
x=embedding(x)
x=layers.GlobalAveragePooling1D()(x)
outputs = layers.Dense(1,activation="sigmoid")(x)
model_1 = tf.keras.Model(inputs, outputs, name="model_1_dense")

In [36]:
model_1.summary()

Model: "model_1_dense"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 1)]               0         
                                                                 
 text_vectorization_1 (TextV  (None, 15)               0         
 ectorization)                                                   
                                                                 
 embedding (Embedding)       (None, 15, 128)           1280000   
                                                                 
 global_average_pooling1d (G  (None, 128)              0         
 lobalAveragePooling1D)                                          
                                                                 
 dense (Dense)               (None, 1)                 129       
                                                                 
Total params: 1,280,129
Trainable params: 1,280,129
N

In [37]:
# compile the model
model_1.compile(loss="binary_crossentropy",
                optimizer=tf.keras.optimizers.Adam(),
                metrics=["accuracy"])

In [38]:
#Fit the model
model_1_history = model_1.fit(x=train_sentences,
                              y=train_labels,
                              epochs = 5,
                              validation_data=(val_sentences,val_labels),
                              callbacks=[create_tensorboard_callback(dir_name=SAVE_DIR, experiment_name = "model_1_dense")])


Saving TensorBoard log files to: model_logs/model_1_dense/20230425-141708
Epoch 1/5
215/215 [==============================] - 11s 38ms/step - loss: 0.6128 - accuracy: 0.6976 - val_loss: 0.5387 - val_accuracy: 0.7520
Epoch 2/5
215/215 [==============================] - 6s 30ms/step - loss: 0.4424 - accuracy: 0.8183 - val_loss: 0.4695 - val_accuracy: 0.7887
Epoch 3/5
215/215 [==============================] - 5s 25ms/step - loss: 0.3482 - accuracy: 0.8603 - val_loss: 0.4555 - val_accuracy: 0.7913
Epoch 4/5
215/215 [==============================] - 7s 30ms/step - loss: 0.2859 - accuracy: 0.8907 - val_loss: 0.4637 - val_accuracy: 0.7900
Epoch 5/5
215/215 [==============================] - 6s 28ms/step - loss: 0.2386 - accuracy: 0.9129 - val_loss: 0.4783 - val_accuracy: 0.7861


In [39]:
# model_1_results = calculate_results(y_true=val_labels,
                                    #  y_pred=)
model_1.evaluate(val_sentences, val_labels)

24/24 [==============================] - 0s 2ms/step - loss: 0.4783 - accuracy: 0.7861


[0.4783346354961395, 0.7860892415046692]

In [40]:
model_1_pred_probs = model_1.predict(val_sentences)
model_1_pred_probs

24/24 [==============================] - 0s 2ms/step


array([[4.10456419e-01],
       [8.08309436e-01],
       [9.97573078e-01],
       [1.21789999e-01],
       [1.24668621e-01],
       [9.38309252e-01],
       [9.07726347e-01],
       [9.92980301e-01],
       [9.64888811e-01],
       [2.69339532e-01],
       [1.24656744e-01],
       [6.62143707e-01],
       [4.27705683e-02],
       [2.32076451e-01],
       [4.66512097e-03],
       [1.21476054e-01],
       [2.56373044e-02],
       [8.12414065e-02],
       [2.35865325e-01],
       [5.08385837e-01],
       [8.86727691e-01],
       [4.67737801e-02],
       [3.87625605e-01],
       [8.35796893e-02],
       [9.54277992e-01],
       [9.98874724e-01],
       [3.85287069e-02],
       [6.97113872e-02],
       [2.89380774e-02],
       [1.83015257e-01],
       [5.48720598e-01],
       [2.68683255e-01],
       [4.78928864e-01],
       [2.07033306e-01],
       [4.77471501e-01],
       [5.88809513e-02],
       [9.94453192e-01],
       [1.46143258e-01],
       [3.38442400e-02],
       [9.98769641e-01],


In [41]:
# model_1_results = calculate_results(y_true=val_labels,
#                                      y_pred=model_1_pred_probs)
# model_1_results

In [42]:
val_labels

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,

In [43]:
model_1_preds = tf.squeeze(tf.round(model_1_pred_probs))
model_1_preds

<tf.Tensor: shape=(762,), dtype=float32, numpy=
array([0., 1., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0.,
       0., 1., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1.,
       0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 1., 1., 1., 1., 0.,
       1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       1., 1., 1., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 0., 0.,
       1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0.,
       0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0

In [44]:
model_1_results = calculate_results(y_true=val_labels,
                                     y_pred=model_1_preds)
model_1_results

{'accuracy': 78.60892388451444,
 'precision': 0.7920916944370863,
 'recall': 0.7860892388451444,
 'f1': 0.7827032509906072}

In [45]:
import numpy as np
np.array(list(model_1_results.values())) > np.array(list(baseline_results.values()))

array([False, False, False, False])

In [46]:
baseline_results

{'accuracy': 79.26509186351706,
 'precision': 0.8111390004213173,
 'recall': 0.7926509186351706,
 'f1': 0.7862189758049549}

In [47]:
words_in_vocab

['',
 '[UNK]',
 'the',
 'a',
 'in',
 'to',
 'of',
 'and',
 'i',
 'is',
 'for',
 'on',
 'you',
 'my',
 'with',
 'it',
 'that',
 'at',
 'by',
 'this',
 'from',
 'be',
 'are',
 'was',
 'have',
 'like',
 'as',
 'up',
 'so',
 'just',
 'but',
 'me',
 'im',
 'your',
 'not',
 'amp',
 'out',
 'its',
 'will',
 'an',
 'no',
 'has',
 'fire',
 'after',
 'all',
 'when',
 'we',
 'if',
 'now',
 'via',
 'new',
 'more',
 'get',
 'or',
 'about',
 'what',
 'he',
 'people',
 'news',
 'been',
 'over',
 'one',
 'how',
 'dont',
 'they',
 'who',
 'into',
 'were',
 'do',
 'us',
 '2',
 'can',
 'video',
 'emergency',
 'there',
 'disaster',
 'than',
 'police',
 'would',
 'his',
 'still',
 'her',
 'some',
 'body',
 'storm',
 'crash',
 'burning',
 'suicide',
 'back',
 'man',
 'california',
 'why',
 'time',
 'them',
 'had',
 'buildings',
 'rt',
 'first',
 'cant',
 'see',
 'got',
 'day',
 'off',
 'our',
 'going',
 'nuclear',
 'know',
 'world',
 'bomb',
 'fires',
 'love',
 'killed',
 'go',
 'attack',
 'youtube',
 'dead

In [48]:
model_1.summary()

Model: "model_1_dense"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 1)]               0         
                                                                 
 text_vectorization_1 (TextV  (None, 15)               0         
 ectorization)                                                   
                                                                 
 embedding (Embedding)       (None, 15, 128)           1280000   
                                                                 
 global_average_pooling1d (G  (None, 128)              0         
 lobalAveragePooling1D)                                          
                                                                 
 dense (Dense)               (None, 1)                 129       
                                                                 
Total params: 1,280,129
Trainable params: 1,280,129
N

In [49]:
#can visualize the results in https://projector.tensorflow.org/

In [50]:
# RNN

In [51]:
# Model 2 : LSTM (long short tern momory)

In [52]:
# creating LSTM model
from tensorflow.keras import layers
inputs = layers.Input(shape=(1,), dtype="string")
x =  text_vectorizer(inputs)
x = embedding(x)
# x = layers.LSTM(64 , return_sequences=True)(x)
x = layers.LSTM(64)(x)
# x = layers.Dense(64, activation="relu")(x)
outputs = layers.Dense(1, activation="sigmoid")(x)
print(outputs.shape)
model_2 = tf.keras.Model(inputs,outputs,name="model_2_LSTM")

(None, 1)


In [53]:
model_2.summary()

Model: "model_2_LSTM"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 1)]               0         
                                                                 
 text_vectorization_1 (TextV  (None, 15)               0         
 ectorization)                                                   
                                                                 
 embedding (Embedding)       (None, 15, 128)           1280000   
                                                                 
 lstm (LSTM)                 (None, 64)                49408     
                                                                 
 dense_1 (Dense)             (None, 1)                 65        
                                                                 
Total params: 1,329,473
Trainable params: 1,329,473
Non-trainable params: 0
____________________________________________

In [54]:
# compiling the model
model_2.compile(loss="binary_crossentropy",optimizer=tf.keras.optimizers.Adam(),metrics=["accuracy"])

In [55]:
# fit the model
model_2_history = model_2.fit(train_sentences,train_labels,epochs=5,
                              validation_data=(val_sentences,val_labels),
                              callbacks=[create_tensorboard_callback(SAVE_DIR,"model_2_LSTM")])

Saving TensorBoard log files to: model_logs/model_2_LSTM/20230425-141753
Epoch 1/5
215/215 [==============================] - 13s 45ms/step - loss: 0.2223 - accuracy: 0.9202 - val_loss: 0.5577 - val_accuracy: 0.7822
Epoch 2/5
215/215 [==============================] - 10s 44ms/step - loss: 0.1554 - accuracy: 0.9429 - val_loss: 0.6361 - val_accuracy: 0.7861
Epoch 3/5
215/215 [==============================] - 9s 42ms/step - loss: 0.1273 - accuracy: 0.9508 - val_loss: 0.6649 - val_accuracy: 0.7887
Epoch 4/5
215/215 [==============================] - 9s 42ms/step - loss: 0.1018 - accuracy: 0.9618 - val_loss: 0.9107 - val_accuracy: 0.7822
Epoch 5/5
215/215 [==============================] - 9s 41ms/step - loss: 0.0857 - accuracy: 0.9664 - val_loss: 0.9432 - val_accuracy: 0.7730


In [56]:
model_2_pred_probs = model_2.predict(val_sentences)
model_2_pred_probs[:10]

24/24 [==============================] - 1s 5ms/step


array([[3.4225530e-03],
       [5.9813970e-01],
       [9.9986118e-01],
       [6.7216463e-02],
       [6.4441696e-04],
       [9.9909657e-01],
       [8.3467603e-01],
       [9.9991012e-01],
       [9.9982828e-01],
       [7.8580308e-01]], dtype=float32)

In [57]:
model_2_preds = tf.squeeze(tf.round(model_2_pred_probs))
model_2_preds[:10]

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 1., 1., 0., 0., 1., 1., 1., 1., 1.], dtype=float32)>

In [58]:
model_2_results = calculate_results(y_true=val_labels,
                                    y_pred = model_2_preds)
model_2_results

{'accuracy': 77.29658792650919,
 'precision': 0.7750482481613202,
 'recall': 0.7729658792650919,
 'f1': 0.7707112186521387}

In [59]:
baseline_results

{'accuracy': 79.26509186351706,
 'precision': 0.8111390004213173,
 'recall': 0.7926509186351706,
 'f1': 0.7862189758049549}

In [60]:
# Model 3: GRU(gated recurrent unit)
from tensorflow.keras import layers
inputs = layers.Input(shape=(1,), dtype="string")
x =  text_vectorizer(inputs)
x = embedding(x)
# x = layers.GRU(64 , return_sequences=True)(x)
# x = layers.LSTM(64 , return_sequences=True)(x)
x = layers.GRU(64)(x)
# x = layers.Dense(64, activation="relu")(x)
# x = layers.GlobalAveragePooling1D()(x)
outputs = layers.Dense(1, activation="sigmoid")(x)
# print(outputs.shape)
model_3 = tf.keras.Model(inputs,outputs,name="model_3_GRU")

In [61]:
model_3.summary()

Model: "model_3_GRU"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_3 (InputLayer)        [(None, 1)]               0         
                                                                 
 text_vectorization_1 (TextV  (None, 15)               0         
 ectorization)                                                   
                                                                 
 embedding (Embedding)       (None, 15, 128)           1280000   
                                                                 
 gru (GRU)                   (None, 64)                37248     
                                                                 
 dense_2 (Dense)             (None, 1)                 65        
                                                                 
Total params: 1,317,313
Trainable params: 1,317,313
Non-trainable params: 0
_____________________________________________

In [62]:
# copile the model
model_3.compile(loss="binary_crossentropy",
                optimizer=tf.keras.optimizers.Adam(),
                metrics=["accuracy"])

In [63]:
# fit the model
model_3_history = model_3.fit(train_sentences,train_labels,epochs=5,
                              validation_data=(val_sentences,val_labels),
                              callbacks=[create_tensorboard_callback(SAVE_DIR,"model_2_LSTM")])

Saving TensorBoard log files to: model_logs/model_2_LSTM/20230425-141919
Epoch 1/5
215/215 [==============================] - 12s 45ms/step - loss: 0.1634 - accuracy: 0.9371 - val_loss: 0.7610 - val_accuracy: 0.7769
Epoch 2/5
215/215 [==============================] - 9s 43ms/step - loss: 0.0823 - accuracy: 0.9705 - val_loss: 0.8161 - val_accuracy: 0.7651
Epoch 3/5
215/215 [==============================] - 16s 74ms/step - loss: 0.0730 - accuracy: 0.9704 - val_loss: 0.9186 - val_accuracy: 0.7756
Epoch 4/5
215/215 [==============================] - 13s 61ms/step - loss: 0.0592 - accuracy: 0.9749 - val_loss: 1.1168 - val_accuracy: 0.7743
Epoch 5/5
215/215 [==============================] - 8s 39ms/step - loss: 0.0546 - accuracy: 0.9749 - val_loss: 1.0791 - val_accuracy: 0.7690


In [64]:
model_3_pred_probs = model_3.predict(val_sentences)
model_3_pred_probs[:10]

24/24 [==============================] - 1s 5ms/step


array([[1.6194516e-03],
       [7.1733570e-01],
       [9.9989247e-01],
       [8.1438377e-02],
       [1.0744369e-04],
       [9.9902260e-01],
       [5.5470508e-01],
       [9.9993896e-01],
       [9.9989587e-01],
       [8.4685755e-01]], dtype=float32)

In [65]:
model_3_preds = tf.squeeze(tf.round(model_3_pred_probs))
model_3_preds[:10]

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 1., 1., 0., 0., 1., 1., 1., 1., 1.], dtype=float32)>

In [66]:
model_3_results = calculate_results(y_true=val_labels,
                                    y_pred=model_3_preds)
model_3_results
# baseline_results

{'accuracy': 76.9028871391076,
 'precision': 0.7711368167182066,
 'recall': 0.7690288713910761,
 'f1': 0.7666669868908192}

In [66]:
# model 4: bidirectional RNN 

In [70]:
from tensorflow.keras import layers
inputs = layers.Input(shape=(1,), dtype="string")
x = text_vectorizer(inputs)
x = embedding(x)
# x = layers.Bidirectional(layers.LSTM(64,return_sequences=True))(x)
x = layers.Bidirectional(layers.LSTM(64))(x)
outputs = layers.Dense(1,activation="sigmoid")(x)
model_4 = tf.keras.Model(inputs, outputs, name="model_4_bidirectional")

In [71]:
model_4.summary()

Model: "model_4_bidirectional"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_6 (InputLayer)        [(None, 1)]               0         
                                                                 
 text_vectorization_1 (TextV  (None, 15)               0         
 ectorization)                                                   
                                                                 
 embedding (Embedding)       (None, 15, 128)           1280000   
                                                                 
 bidirectional_2 (Bidirectio  (None, 128)              98816     
 nal)                                                            
                                                                 
 dense_4 (Dense)             (None, 1)                 129       
                                                                 
Total params: 1,378,945
Trainable params: 1,3

In [73]:
#COMPILE
model_4.compile(loss="binary_crossentropy",
                optimizer=tf.keras.optimizers.Adam(),
                metrics=["accuracy"])

In [74]:
#fit the model
model_4_history = model_4.fit(train_sentences,
                              train_labels,
                              epochs=5,
                              validation_data=(val_sentences, val_labels),
                              callbacks=[create_tensorboard_callback(SAVE_DIR,"model_4_bidirectioanl")])

Saving TensorBoard log files to: model_logs/model_4_bidirectioanl/20230425-144258
Epoch 1/5
215/215 [==============================] - 16s 54ms/step - loss: 0.1034 - accuracy: 0.9669 - val_loss: 0.9853 - val_accuracy: 0.7703
Epoch 2/5
215/215 [==============================] - 11s 49ms/step - loss: 0.0547 - accuracy: 0.9752 - val_loss: 1.2973 - val_accuracy: 0.7769
Epoch 3/5
215/215 [==============================] - 15s 68ms/step - loss: 0.0433 - accuracy: 0.9785 - val_loss: 1.4643 - val_accuracy: 0.7651
Epoch 4/5
215/215 [==============================] - 14s 63ms/step - loss: 0.0421 - accuracy: 0.9806 - val_loss: 1.5134 - val_accuracy: 0.7703
Epoch 5/5
215/215 [==============================] - 12s 54ms/step - loss: 0.0430 - accuracy: 0.9799 - val_loss: 1.1568 - val_accuracy: 0.7717


In [75]:
model_4_pred_probs = model_4.predict(val_sentences)
model_4_pred_probs[:10]

24/24 [==============================] - 1s 8ms/step


array([[1.30496165e-02],
       [7.66102195e-01],
       [9.99538600e-01],
       [3.07770878e-01],
       [5.11308644e-05],
       [9.98651624e-01],
       [7.91032791e-01],
       [9.99864817e-01],
       [9.99645591e-01],
       [9.66318905e-01]], dtype=float32)

In [76]:
model_4_preds = tf.squeeze(tf.squeeze(tf.round(model_4_pred_probs)))
model_4_preds[:10]

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 1., 1., 0., 0., 1., 1., 1., 1., 1.], dtype=float32)>

In [77]:
model_4_results = calculate_results(y_true=val_labels,
                                    y_pred=model_4_preds)
model_4_results

{'accuracy': 77.16535433070865,
 'precision': 0.773559668677779,
 'recall': 0.7716535433070866,
 'f1': 0.7694523344399302}

In [78]:
model_3_results

{'accuracy': 76.9028871391076,
 'precision': 0.7711368167182066,
 'recall': 0.7690288713910761,
 'f1': 0.7666669868908192}

In [79]:
model_2_results

{'accuracy': 77.29658792650919,
 'precision': 0.7750482481613202,
 'recall': 0.7729658792650919,
 'f1': 0.7707112186521387}

In [80]:
baseline_results

{'accuracy': 79.26509186351706,
 'precision': 0.8111390004213173,
 'recall': 0.7926509186351706,
 'f1': 0.7862189758049549}